### ISSUE TITLE
Cannot find var "mk-get-id-from-coll"

### ISSUE THREAD

**Issue by sittim** [dvingo/dv.fulcro-template#4]
Tried to run it and getting error below:        

```
at clojure.main.main(main.java:38)
Caused by: java.lang.RuntimeException: No such var: cu/mk-get-id-from-coll
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7388)
        at clojure.lang.Compiler.resolve(Compiler.java:7358)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7319)
        at clojure.lang.Compiler.analyze(Compiler.java:6768)
        ... 157 more
```

I looked in the repo and did not find definition of the var.  Looking here: https://github.com/dvingo/my-clj-utils/blob/master/src/main/dv/crux_util.clj, the var does not seem to exist.

**Comment by dvingo** [comment]
Thanks for the report @sittim - I have a pending update to this template to address that, should have some time in the next day or two to get it addressed.

**Comment by sittim** [comment]
OK, sounds good.

**Comment by dvingo** [comment]
hey @sittim just pushed an update and tested with the +all args and things are working again.

**Comment by sittim** [comment]
Yes, it works, thank you ...
